version: '3'
services:
  graphql-federation:
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    restart: always
    depends_on:
      - problemreport
      - snowdepth
      - temperature
    environment:
      API_GQL_FEDERATION_PORT: '8989'
      API_GQL_FEDERATION_SVCS: 'problemreport:8383,snowdepth:8282,temperature:8181'
    ports:
      - '8989:8989'


  problemreport:
    image: "iot-for-tillgenglighet/api-problemreport:latest"
    restart: always
    depends_on:
      - rabbitmq
      - postgresdb
    links:
      - rabbitmq
      - postgresdb
    environment:
      PROBLEMREPORT_DB_HOST: "postgresdb"
      PROBLEMREPORT_DB_USER: "testuser"
      PROBLEMREPORT_DB_NAME: "federation-test-db"
      PROBLEMREPORT_DB_PASSWORD: "testpass"
      PROBLEMREPORT_DB_SSLMODE: "disable"
      PROBLEMREPORT_API_PORT: "8383"
      RABBITMQ_HOST: "rabbitmq"

    ports:
      - "8383"
    
  snowdepth:
    image: 'iot-for-tillgenglighet/api-snowdepth:latest'
    restart: always
    depends_on:
      - rabbitmq
      - postgresdb
    links:
      - rabbitmq
      - postgresdb
    environment:
      SNOWDEPTH_DB_HOST: 'postgresdb'
      SNOWDEPTH_DB_USER: 'testuser'
      SNOWDEPTH_DB_NAME: 'federation-test-db'
      SNOWDEPTH_DB_PASSWORD: 'testpass'
      SNOWDEPTH_DB_SSLMODE: 'disable'
      SNOWDEPTH_API_PORT: '8282'
      RABBITMQ_HOST: 'rabbitmq'
      
    ports:
      - '8282'


  temperature:
    image: 'iot-for-tillgenglighet/api-temperature:latest'
    restart: always
    depends_on:
      - rabbitmq
      - postgresdb
    links:
      - rabbitmq
      - postgresdb
    environment:
      TEMPERATURE_DB_HOST: 'postgresdb'
      TEMPERATURE_DB_USER: 'testuser'
      TEMPERATURE_DB_NAME: 'federation-test-db'
      TEMPERATURE_DB_PASSWORD: 'testpass'
      TEMPERATURE_DB_SSLMODE: 'disable'
      TEMPERATURE_API_PORT: '8181'
      RABBITMQ_HOST: 'rabbitmq'
      
    ports:
      - '8181'


  postgresdb:
    image: 'iot-for-tillgenglighet/testdb-postgres:latest'
    restart: always
    environment:
      POSTGRES_DB: 'federation-test-db'
      POSTGRES_USER: 'testuser'
      POSTGRES_PASSWORD: 'testpass'
    ports:
      - '5432'


  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    ports:
      - '4369'
      - '5672'
      - '25672'
      - '15672'
    volumes:
      - 'rabbitmq_data:/bitnami'


volumes:
  rabbitmq_data:
    driver: local
