version: '3'
services:
  graphql-federation:
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    restart: always
    depends_on:
      - problemreport
      - snowdepth
      - temperature
    environment:
      API_GQL_FEDERATION_PORT: '8080'
      API_GQL_FEDERATION_SVCS: 'deviceregistry:8484,problemreport:8383,snowdepth:8282,temperature:8181'
    ports:
      - '8088:8080'


  deviceregistry:
    image: 'ghcr.io/diwise/iot-device-registry:prod-80fc3d1307891da2494602f8b3766bcef59a7811'
    restart: always
    environment:
      DIWISE_SQLDB_HOST: 'postgresdb'
      DIWISE_SQLDB_USER: 'testuser'
      DIWISE_SQLDB_NAME: 'federation-test-db'
      DIWISE_SQLDB_PASSWORD: 'testpass'
      DIWISE_SQLDB_SSLMODE: 'disable'
      RABBITMQ_HOST: "rabbitmq"
      SERVICE_PORT: "8484"

    ports:
      - "8484"


  problemreport:
    image: "ghcr.io/diwise/api-problemreport:prod-4f36034ad12626387d3f6cb2ebb4262cbc355412"
    restart: always
    depends_on:
      - rabbitmq
      - postgresdb
    links:
      - rabbitmq
      - postgresdb
    environment:
      PROBLEMREPORT_DB_HOST: "postgresdb"
      PROBLEMREPORT_DB_USER: "testuser"
      PROBLEMREPORT_DB_NAME: "federation-test-db"
      PROBLEMREPORT_DB_PASSWORD: "testpass"
      PROBLEMREPORT_DB_SSLMODE: "disable"
      PROBLEMREPORT_API_PORT: "8383"
      RABBITMQ_HOST: "rabbitmq"

    ports:
      - "8383"
    
  snowdepth:
    image: 'ghcr.io/diwise/api-snowdepth:prod-da13a4756404f6a8c6b55fe646a9fc9fcd92570b'
    restart: always
    depends_on:
      - rabbitmq
      - postgresdb
    links:
      - rabbitmq
      - postgresdb
    environment:
      SNOWDEPTH_DB_HOST: 'postgresdb'
      SNOWDEPTH_DB_USER: 'testuser'
      SNOWDEPTH_DB_NAME: 'federation-test-db'
      SNOWDEPTH_DB_PASSWORD: 'testpass'
      SNOWDEPTH_DB_SSLMODE: 'disable'
      SNOWDEPTH_API_PORT: '8282'
      RABBITMQ_HOST: 'rabbitmq'
      
    ports:
      - '8282'


  temperature:
    image: 'ghcr.io/diwise/api-temperature:prod-4bbd88ac59faa7a69b4882d533c8f7c289850646'
    restart: always
    depends_on:
      - rabbitmq
      - postgresdb
    links:
      - rabbitmq
      - postgresdb
    environment:
      TEMPERATURE_DB_HOST: 'postgresdb'
      TEMPERATURE_DB_USER: 'testuser'
      TEMPERATURE_DB_NAME: 'federation-test-db'
      TEMPERATURE_DB_PASSWORD: 'testpass'
      TEMPERATURE_DB_SSLMODE: 'disable'
      TEMPERATURE_API_PORT: '8181'
      RABBITMQ_HOST: 'rabbitmq'
      
    ports:
      - '8181'


  postgresdb:
    image: 'ghcr.io/diwise/test-db-postgresql:prod-824e7cffd65dd3766c88441a48cffd5b2acd55f2'
    restart: always
    environment:
      POSTGRES_DB: 'federation-test-db'
      POSTGRES_USER: 'testuser'
      POSTGRES_PASSWORD: 'testpass'
    ports:
      - '5432'


  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    ports:
      - '4369'
      - '5672'
      - '25672'
      - '15672'
    volumes:
      - 'rabbitmq_data:/bitnami'


volumes:
  rabbitmq_data:
    driver: local
